### ISSUE TITLE
Define the Service Approval Accelerator for PostgreSQL on Microsoft Azure

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#21]
### Description

Define the **Service Approval Accelerator for PostgreSQL** using the [Service Approval Accelerator Template](https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md) for reference.

### Tasks

- [ ] Create an `azure\postgresql` folder structure in the [Cloud Services Certification project root](https://github.com/finos/cloud-service-certification).
- [ ] Define the **Service Approval Accelerator for PostgreSQL** as `markdown`.
- [ ] Commit **Service Approval Accelerator for PostgreSQL** to `azure\postgresql` folder .
- [ ] Raise PR to project team for review and merge. 

### Service Approval Accelerator Template
The following is the **Service Approval Accelerator Template** on GitHub.

https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md

**Comment by mcleo-d** [comment]
Hi @git-hub-forwork1 

I've created this Cloud Service Certification story for you to review and provide feedback in the comments.

You'll notice the story has the **feature-writing** label applied until the content of this story is reviewed and accepted by you.

Please let me know if anything needs to be amended so I can edit the main content and we can take forward with the CSC group.

Speak soon 👍 

James

**Comment by peterrhysthomas** [comment]
Can this be reassigned to @danizheleva
