### ISSUE TITLE
Add "New Cloud Service Request" markdown template to CSC ISSUE_TEMPLATE folder

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#23]
### Description
All cloud services that are contributed to Cloud Service Certification must include a standard set of artefacts for the contribution to be considered done. 

This work item is to add a "New Cloud Service Request" template as markdown to the Cloud Service Certification `ISSUE_TEMPLATE` folder as highlighted below.

This means, for every request that's made for a new cloud service, the issue template will include the artefacts needed for the issue to be considered done when the item is picked contributed.

https://github.com/finos/cloud-service-certification/tree/master/.github/ISSUE_TEMPLATE

### Work Items to Complete

- [ ] Create new `Cloud_service.md` file in https://github.com/finos/cloud-service-certification/tree/master/.github/ISSUE_TEMPLATE
- [ ] Create new `Cloud_service.md` markdown template using the MD format below   

```
---
name: <emoji_here> <template title>
about: <description>

---

## <template title>

<description of services contribution requirements>

- [ ] <service contribution requirement>
- [ ] <service contribution requirement>
- [ ] <service contribution requirement>
- [ ] <service contribution requirement>
- [ ] <service contribution requirement>

```
- [ ] Add appropriate titles, text and contribution requirements to the MD template.
- [ ] Raise PR for `Cloud_service.md` add to https://github.com/finos/cloud-service-certification/tree/master/.github/ISSUE_TEMPLATE

### Standard set of artefacts to include
The following lists the artefacts required with each service request for the associated service contribution to be completed. 

These should be added to the template as the `<service contribution requirement>`

- [ ] Cloud Platform Target
- [ ] Service Name
- [ ] Service Approval Accelerator Definition 
- [ ] Control Framework Definition
- [ ] Test Cases Created
- [ ] Deployment Scripts Created
- [ ] Gherkin Scripts Created

**Comment by mcleo-d** [comment]
@git-hub-forwork1 - I've added the skeleton of this story if you'd like to help me refine the definition and acceptance criteria before we allocate to the group for completion. 

Feel free to feedback directly in the comments and I'll update the issue description accordingly. 

👍

**Comment by mcleo-d** [comment]
Hi @git-hub-forwork1 

I've created this Cloud Service Certification story for you to review and provide feedback in the comments.

You'll notice the story has the **feature-writing** label applied until the content of this story is reviewed and accepted by you.

Please let me know if anything needs to be amended so I can edit the main content and we can take forward with the CSC group.

Speak soon 👍 

James

**Comment by git-hub-forwork1** [comment]
This is great and is what we were looking for.  I believe having this will help contributors feel more enabled to make requests for new services and just start it up.
Thanks @mcleo-d

**Comment by mcleo-d** [comment]
Thanks @git-hub-forwork1. I've removed the **feature-writing** label and have added **help wanted** and **good first issue** 👍 

I've also moved to the prioritised column in the project kanban 😄
* https://github.com/orgs/finos/projects/1

**Comment by fleadsom** [comment]
@mcleo-d created PR #46 - doesn't seem to be linking to the issue however - might be access rights... Are you able to edit -> link issue?

**Comment by mcleo-d** [comment]
Issue linked @fleadsom. Thanks for #46 and the comment 👍

**Comment by mcleo-d** [comment]
@fleadsom and @git-hub-forwork1 - I have added this issue and PR #46 to the CSC agenda for 2nd July #45. I'm looking forward to introducing this project accelerator to the group 👍

**Comment by fleadsom** [comment]
@mcleo-d updated the PR with a merge of the control framework and test case as discussed. @abdullahgarcia to review
