### ISSUE TITLE
Define the Control Framework for PostgreSQL on Microsoft Azure

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#24]
### Description

Define the **Control Framework for PostgreSQL** using the [CSC Control Spreadsheet ](https://github.com/finos/cloud-service-certification/blob/master/templates/CSC%20control%20spreadsheet.xlsx) for reference.

### Tasks

- [x] Create an `azure\postgresql` folder structure in the [Cloud Services Certification project root](https://github.com/finos/cloud-service-certification).
- [x] Define the **Control Framework for PostgreSQL** as `markdown`.
- [x] Commit **Control Framework for PostgreSQL** to `azure\postgresql` folder .
- [x] Raise PR to project team for review and merge. 

### CSC Control Spreadsheet Template
The following is the **CSC Control Spreadsheet Template** on GitHub.

https://github.com/finos/cloud-service-certification/blob/master/templates/CSC%20control%20spreadsheet.xlsx

**Comment by mcleo-d** [comment]
Hi @git-hub-forwork1 

I've created this Cloud Service Certification story for you to review and provide feedback in the comments.

You'll notice the story has the **feature-writing** label applied until the content of this story is reviewed and accepted by you.

Please let me know if anything needs to be amended so I can edit the main content and we can take forward with the CSC group.

Speak soon 👍 

James

**Comment by danizheleva** [comment]
@mcleo-d could you please re-assign this ticket to me

**Comment by mcleo-d** [comment]
Done @danizheleva - Thanks! :)

**Comment by mcleo-d** [comment]
Another issue closed @danizheleva! 👏 👏 👏  💯
