### ISSUE TITLE
18 June 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#42]
## Date
Thursday 18th June 2020 - 10am EST / 3pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Agenda
- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Review action items from previous meetings
- [x] _**Pull Request Review**_ : Updating template table to include new categories and extra detail #39 - @danizheleva 🎉 👏  
- [x] _**Pull Request Approval**_ : Group to approve @mcleo-d changes to meeting template - #43
- [x]  @alfredtommy to introduce the Searce Security Command Center Service team for GCP to the group - (5 mins)
- [x] _**Question**_ : What are the contributions steps and expectations for submitting new service Infrastructure as Code to CSC for AWS, Azure and GCP? - @git-hub-forwork1 and @peterrhysthomas to answer.
- [x] Requests Reminder
  - **Help Wanted** by @pudern for Google Cloud Platform priorities.
  - **Request** by @git-hub-forwork1 for CSC group to start writing contribution stories in [CSC GitHub Issues](https://github.com/finos/cloud-service-certification/issues).  
  - **Request** by @git-hub-forwork1 for CSC members to collaborate on - _New AWS Cloud Service request AWS EventBridge_ - #36
- [x] AOB, Q&A & Adjourn (5mins)

### Previous Actions #35 
- [x] @danizheleva and @alfredtommy to incorporate **Service Approval Accelerator Template** suggestions in https://github.com/finos/cloud-service-certification/issues/35#issuecomment-638836705 into https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md with @git-hub-forwork1 via pull request - #37
- [x] @git-hub-forwork1 and @peterrhysthomas to coordinate tidying https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md to remove technology references to enable white labelling for multiple service types - #38
- [x] @iantivey to review https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md and feedback into the comments of this issue if required. 
- [x] @mcleo-d to review CSC meeting and capture decisions / actions and add to this issue.

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by mcleo-d** [comment]
@git-hub-forwork1 and @peterrhysthomas - Can you review the CSC agenda above and add your additions / amendments to the issue body direct or to the comments of this issue?

I would like to get the agenda emailed to the CSC group this evening ready for tomorrow's meeting.

Many thanks!

James.

**Comment by mcleo-d** [comment]
@danizheleva - I've added you to the agenda to walk through the following PR that was raised and merged. It's time to celebrate with the team 👏👏 💯💯💯 

> **Pull Request Review** : Updating template table to include new categories and extra detail #39 - @danizheleva 🎉 👏

**Comment by mcleo-d** [comment]
@iantivey - Are you able to bring your feedback to the meeting regarding the action taken in #35 below ... 

> @iantivey to review https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md and feedback into the comments of this issue if required.

Many thanks!

James.

**Comment by fleadsom** [comment]
Hi

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by peterrhysthomas** [comment]
hello

**Comment by alfredtommy** [comment]
hello

**Comment by danizheleva** [comment]
hello

**Comment by jamilmina1** [comment]
Hello

**Comment by ignaciotgomez** [comment]
Hello

**Comment by brooklynrob** [comment]
Hello.

**Comment by ksmithatsuse** [comment]
Hi All, looking forward to my first call be gentle ;-)

**Comment by git-hub-forwork1** [comment]
Hello

**Comment by mattgallcitihub** [comment]
hi

**Comment by pudern** [comment]
hello

**Comment by mcleo-d** [comment]
@dumrauf and @mikejstevenson - Can you respond to me in the comments below to register yourselves on today's call. Thanks! 🎸🎶🎶🎶

**Comment by ofercloudify** [comment]
Hello, thanks for letting me in. Ofer Yarom (Cloudify)

**Comment by mikejstevenson** [comment]
Hi James - sorry for the delay!

**Comment by dumrauf** [comment]
Hi James

**Comment by mcleo-d** [comment]
> Couldn't find the following GitHub usernames on file: @ofercloudify, @ksmithatsuse . /CC @aitana16 @maoo @mcleo-d

@aitana16 - I have taken care of this request and am working with @maoo to resolve. Thanks! :)

**Comment by mcleo-d** [comment]
@ksmithatsuse - Do you mind emailing me at help@finos.org so I can add your email address to the Cloud Service Certification group. Many thanks. James 👍

**Comment by mcleo-d** [comment]
@ofercloudify - Do you mind emailing me at help@finos.org so I can add your email address to the Cloud Service Certification group. Many thanks. James 👍
