### ISSUE TITLE
2 July 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#45]
## Date
Thursday 2 July 2020 - 10am EST / 3pm BST

## Untracked attendees
| Name | Firm | Comment |
|----------|-------------|------|
|  |  |  |
|  |  |  |

## Agenda

- [ ] Convene, roll call, welcome new people
- [ ] Review action items from previous meetings... _See Below_
- [ ] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [ ] @peterrhysthomas / @danizheleva Deutsche Bank update of changes made to make OSS delivery pipeline into CSC possible.
- [ ] @fleadsom walkthrough of issue #23 and live review and merge pull request #46 - 'Add "New Cloud Service Request" markdown template to CSC ISSUE_TEMPLATE folder'. 
- [ ] @alfredtommy feedback and progress moving forward with #44 - "Delivery of Google Kubernetes Engine (GKE) Service for GCP including Security Command Center"
- [ ] @anthonygtech to resurface #19 with the objective of determining the priority and work order with the group. 
- [ ] RedShift as gold service example to project README.md - @mcleo-d PR - #47
- [ ] AOB, Q&A & Adjourn (5mins)

## Previous Actions
- [x] @pudern and @alfredtommy to [Create and Lead CSC Issue](https://github.com/finos/cloud-service-certification/issues/new/choose) that introduces GCP Security Command Center Service to CSC project.
  - Focus on a single GCP service use case that's similar to current AWS and Azure focus.
  - GCP Security Command Center Service is the answer, but what is the question?
  - Services contributed to CSC should be able to run anywhere as reusable artefacts.
- [x] Add paragraph to `templates/ServiceApprovalAcceleratorTemplate.md` that explains RedShift technical examples - [Commit Completed](https://github.com/finos/cloud-service-certification/commit/d54a24fd6da9c4f0fcd6646047502982bd507bbe) by @git-hub-forwork1 on call 👍 
- [x] Add RedShift as gold service example to project README.md - @mcleo-d PR - #47
- [ ] @iantivey to review https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md and feedback into the comments of this issue if required - @mattgallcitihub to coordinate activity

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by danizheleva** [comment]
hello

**Comment by pudern** [comment]
hello

**Comment by alfredtommy** [comment]
hello

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by ajwadjaved** [comment]
hii

**Comment by brooklynrob** [comment]
I am here.

**Comment by aitana16** [comment]
hi!

**Comment by asorane** [comment]
Hi, here is Angel from Itau Unibanco

**Comment by abdullahgarcia** [comment]
Hello!

**Comment by junjikatto** [comment]
Hi there!

**Comment by fleadsom** [comment]
hi

**Comment by brooklynrob** [comment]
I was here.

**Comment by mcleo-d** [comment]
@peterrhysthomas - Thanks for hosting Cloud Service Certification on Thursday 👍  Do you mind saying hello below to register yourself on the the call? Thanks!

**Comment by peterrhysthomas** [comment]
hello
