### ISSUE TITLE
16 July 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#49]
## Date
Thursday 16 July 2020 - 10am EST / 3pm BST

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Review action items from previous meetings
- [ ] @alfredtommy and @fleadsom to chair review of **Pull Request for Service Approval Accelerator for GKE service in GCP** #48 to answer the following questions ... 
  1. Are these specific requirements consistent for everybody? 
  2. How do we agree on these in the future rather than everyone taking it away and checking with internal control functions?
- [ ] @git-hub-forwork1 & @peterrhysthomas - Now we are expanding, lets review our [Open Volunteer Roles](https://github.com/finos/cloud-service-certification/wiki#open-volunteer-roles) and ask **Are they still relevant?** and **Do they need updating?**
  - [Compliance Framework Mapping Role](https://github.com/finos/cloud-service-certification/wiki/Compliance-Framework-Mapping-Role)
  - [Cloud Service Certification Documentation Role](https://github.com/finos/cloud-service-certification/wiki/Cloud-Service-Certification-Documentation-Role)
  - [Codified Controls Development Role](https://github.com/finos/cloud-service-certification/wiki/Codified-Controls-Development-Role)
  - [BDD Test Case Development Role](https://github.com/finos/cloud-service-certification/wiki/BDD-Test-Case-Development-Role)
  - [Peer Reviewer Role](https://github.com/finos/cloud-service-certification/wiki/Peer-Reviewer-Role)
  - [Cloud Service Effort Owner ](https://github.com/finos/cloud-service-certification/wiki/Cloud-Service-Effort-Owner)
- [ ] AOB, Q&A & Adjourn (5mins)
  - @danizheleva and @fleadsom representing Deutsche Bank and Cloud Service Certification at [virtual] Cloud London tonight. Register to join and support ... https://www.meetup.com/Cloud-London/events/271178947/

## Previous Actions
- [x] @fleadsom to resolve review changes from @peterrhysthomas on https://github.com/finos/cloud-service-certification/pull/46#discussion_r449041342
- [x] Cloud Service Certification group invited to feedback asynchronously on PR #46
- [x] @fleadsom to merge #46 with @abdullahgarcia once @peterrhysthomas review changes complete. 
- [x] @alfredtommy and @pudern to raise GCP PR related to #44 for asynchronous feedback prior to next group session.
- [x] @anthonygtech to research Red Hat banking client who is willing to represent OpenShift in relation to moving #19 forward.
- [x] Cloud Service Certification group invited to review @mcleo-d changes on #47 prior to PR merge. 

## Action Items
- [ ] Edit project participants in Wiki
- [ ] Working group to review contributions to be setup: starting with GCP GKE

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by jamilmina1** [comment]
hi

**Comment by alfredtommy** [comment]
hello

**Comment by fleadsom** [comment]
hi

**Comment by danizheleva** [comment]
hello

**Comment by mcleo-d** [comment]
Hello 👍

**Comment by junjikatto** [comment]
Hello!

**Comment by njwilliams** [comment]
hi

**Comment by peterrhysthomas** [comment]
hello

**Comment by knewcomerRH** [comment]
hi all

**Comment by fleadsom** [comment]
Actions:

**Comment by mcleo-d** [comment]
> @mcleo-d can you add these to 'actions'?

Done - @fleadsom 👍 

Let me know if you managed to get through the agenda and I'll tick off these tasks too.

Also, regarding _"Edit project participants in Wiki"_, do you think there's value transferring the wiki to the repo as markdown so this work can be done through PRs? 🤔

**Comment by mcleo-d** [comment]
@git-hub-forwork1 - Do you mind saying hello in the comments so I can register your attendance? Thanks 🚀

**Comment by mcleo-d** [comment]
@natishalom - Do you mind saying hello in the comments so I can register your attendance? Thanks 🚀

**Comment by mcleo-d** [comment]
@ofercloudify - Do you mind saying hello in the comments so I can register your attendance? Thanks 🚀

**Comment by ofercloudify** [comment]
hello

**Comment by mcleo-d** [comment]
The following action item was completed on **Wednesday 22nd July 2020** with the outcome referred to in the comments link below.

> - [x] Working group to review contributions to be setup: starting with GCP GKE - https://github.com/finos/cloud-service-certification/pull/48#issuecomment-662448337

**Comment by njwilliams** [comment]
Njwilliams is me.

NIck

**Comment by mcleo-d** [comment]
> Njwilliams is me.

Thanks @Njwilliams. You were tagged in an automatic notification by our meeting attendance bot. 

We've now resolved that issue, thanks!
