### ISSUE TITLE
30 July 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#53]
## Date
Thursday 30 July 2020 - 10am EST / 3pm BST

## Untracked attendees
| Name | Firm | Comment |
|----------|-------------|------|

## Agenda
- [x] Convene, roll call, welcome new people
- [x] Review action items from previous meetings
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] _Review_ : We've had a kanban tidy :)) [Cloud Service Certification Kanban Review](https://github.com/orgs/finos/projects/1)
- [x] _Update_ : @alfredtommy - Service Approval Accelerator for GKE service in GCP #48
- [x] _Discussion_ : @danizheleva - Service Accelerator Template
  - There has been some confusion about the content we should place in the “Measure of Compliance” column. @alfredtommy is currently producing one of the templates so would be interested to see he has thought about this column. Maybe we just need to add more clarity to the template?
- [x] _Review_ : @mcleo-d - Add Your Questions Answered page to the CSC wiki #52
- [x] _Review_ : @mcleo-d - Transfer markdown content from Cloud Service Certification wiki tab on GitHub into a docs folder in the repo #50
- [ ] _Add Items Here_
- [ ] AOB, Q&A & Adjourn (5mins)

## Previous Actions
- [ ] Edit project participants in Wiki #51
- [x] Working group to review contributions to be setup: starting with GCP GKE - https://github.com/finos/cloud-service-certification/pull/48#issuecomment-662448337

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by jamilmina1** [comment]
hello

**Comment by danizheleva** [comment]
hello

**Comment by peterrhysthomas** [comment]
hello

**Comment by junjikatto** [comment]
Hi there!

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by anthonygtech** [comment]
Hi.

**Comment by phtoth** [comment]
Hello!

**Comment by cr20ro20** [comment]
Hi

**Comment by leefaus** [comment]
Hello 👋

**Comment by mcleo-d** [comment]
Hi @cr20ro20 

Thanks for joining the call yesterday. Can you let me know your name and firm so we can note against the meeting?

Many thanks 🚀 

James.

**Comment by cr20ro20** [comment]
Hi James,

I’m Craig Rowe at Cantor Fitzgerald.

Cheers!

**Comment by mcleo-d** [comment]
Hi @leefaus,

During this Cloud Service Certification meeting I took the following action ... 

> @mcleo-d to work with @leefaus on adding compliance as code open policy agent demo to future CSC agenda with the intention of future Armoury collaboration.

Can you take a look at the public FINOS calendar and let me know a date that works for you?https://calendar.google.com/calendar/embed?src=finos.org_fac8mo1rfc6ehscg0d80fi8jig%40group.calendar.google.com&ctz=America%2FNew_York

I look forward to meeting again on Thursday's call 😄  #56 

James.
