### ISSUE TITLE
13 August 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#56]
## Date
Thursday 13 August 2020 - 10am EST / 3pm BST

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|
| | | |

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Review action items from previous meetings
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] @mcleo-d "Nomination of Peter Thomas from Deutsche Bank as Cloud Service Certification Lead Maintainer" #54 
- [x] @mcleo-d Cloud Service Certification Service Contribution Infographic #55 
- [x] @mcleo-d CSC wiki update that unblocks **Edit project participants in Wiki** #51 from PRs #52 #50 
- [x] [Cloud Service Certification Kanban Review](https://github.com/orgs/finos/projects/1)
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Previous Action Items
- [x] @abdullahgarcia to merge GCP GKE pull request with @alfredtommy following successful project review - #48
- [x] @abdullahgarcia to merge #52 #50 wiki docs PRs with @mcleo-d 
- [ ] @danizheleva - To continue with Deutsche Bank Service Accelerator Template for Azure Postgres, skipping over the “Measure of Compliance” column, with the intention to review with the group when ready.
- [ ] @danizheleva - Assess if “Measure of Compliance” column is relevant and remove from Service Accelerator Template if decided not needed with the group.
- [x] @mcleo-d to work with @leefaus on adding compliance as code open policy agent demo to future CSC agenda with the intention of future Armoury collaboration - https://github.com/finos/cloud-service-certification/issues/53#issuecomment-672040675

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by pudern** [comment]
hello

**Comment by leefaus** [comment]
👋  hello

**Comment by cr20ro20** [comment]
hi

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by njwilliams** [comment]
yo

**Comment by danizheleva** [comment]
hi

**Comment by anthonygtech** [comment]
Hello.

**Comment by adamj-codethink** [comment]
Hey o/

**Comment by abdullahgarcia** [comment]
Hi!
