### ISSUE TITLE
27 August 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by peterrhysthomas** [finos/cloud-service-certification#59]
## Date
Thursday 27th Aug 2020 - 10am EST / 3pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda

- [ ] Convene, roll call, welcome new people
- [ ] Review action items from previous meetings
- [ ] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues/56
- [ ] [Cloud Service Certification Kanban Review](https://github.com/orgs/finos/projects/1)

- [ ] Discussion of infographic, FAQ and intro documentation #55
- [ ] Discussion on referencing documentation/code in other repositories
- [ ] Discussion on OSS Forum
- [ ] Discussion on initial contributions from CodeThink
- [ ] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] Infographic, FAQ and intro documentation #55, interested parties to comment on issue thread and a follow up session to be arranged
- [ ] CodeThink to investigate first contribution options - possible Kubernetes for AWS or Azure or extension of GCP content
- [ ] Team to consider options for OSS Forum, details to be provided by Tosha
- [ ] Discussion at next session regarding linking/referencing code and documentation outside of Finos structure, eg Redhat OSS or Citihub OSS

## Previous Action Items
- [x] @danizheleva - To continue with Deutsche Bank Service Accelerator Template for Azure Postgres, skipping over the “Measure of Compliance” column, with the intention to review with the group when ready.
- [x] @danizheleva - Assess if “Measure of Compliance” column is relevant and remove from Service Accelerator Template if decided not needed with the group.
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by jamilmina1** [comment]
Hello!

**Comment by danizheleva** [comment]
hello

**Comment by toshaellison** [comment]
here

**Comment by adamj-codethink** [comment]
Hi o/

**Comment by anthonygtech** [comment]
Hello.

**Comment by leefaus** [comment]
good morning!

**Comment by RichardWagener365** [comment]
Hi

**Comment by fleadsom** [comment]
hi 👍

**Comment by toshaellison** [comment]
As discussed on the call, this year's [Open Source Strategy Forum (OSSF)](https://events.linuxfoundation.org/open-source-strategy-forum/) will be virtual and will take place on **November 12th & 13th**. This is a great opportunity to highlight recent work and developments in the Cloud Service Certification project and attract new contributors.

We are flexible on format (presentation, panel discussion, demo, hands-on working session, deep dive into specific service or approach, etc.) and can also more than one session if it makes sense to do, for example, an overview and a deep dive.

Please consider what/how to present and let me know so that we can lock in a slot and begin to promote. We'd really like to represent our diverse community so please also bear that in mind as you think about possible presenters.
