### ISSUE TITLE
10 September 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#61]
## Date
Thursday 10 September 2020 - 10am EST / 3pm BST

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|
| Alessandro Petroni | RedHat | @apetroni - Can you register yourself in the comments below 👇 😄 |
| Alfred Tommy | Searce | @alfredtommy - Can you register yourself in the comments below 👇 😄  |
| Junji Katto | Itaú  | @junjikatto - Can you register yourself in the comments below 👇 😄  |
| Pedro Henrique Toth | Itaú  |  |

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [ ] Review action items from previous meetings
- [x] @danizheleva - Pull request : Service Accelerator Template completed for PostgreSQL on Microsoft Azure #60
- [x] @alfredtommy and @abdullahgarcia - GCP GKE #48 / AWS Kubernetes update and next steps  
- [ ] [Cloud Service Certification Kanban Review](https://github.com/orgs/finos/projects/1)
- [ ] AOB, Q&A & Adjourn

## Previous Action Items
- [x] Infographic, FAQ and intro documentation #55, interested parties to comment on issue thread and a follow up session to be arranged
- [x] CodeThink to investigate first contribution options - possible Kubernetes for AWS or Azure or extension of GCP content
- [x] Team to consider options for OSS Forum, details to be provided by @toshaellison 
- [ ] Discussion at next session regarding linking/referencing code and documentation outside of Finos structure, eg Redhat OSS or Citihub OSS

## Action Items
- [ ] @peterrhysthomas to create an Epic in CSC GitHub Issues that represents the delivery and acceptance criteria of the Kubernetes service across all supported cloud services
- [ ] @alfredtommy to create an issue in GitHub that represents the technical delivery of the Kubernetes service for GCP to supports the pull request that's being raised
- [ ] @abdullahgarcia to create an issue in GitHub that supports the creation of the Service Accelerator Template for the Kubernetes service in AWS
- [ ] @leefaus to create a GitHub issue that represents the integration of [Pulumi](https://www.pulumi.com/) for BDD test purposes against the next appropriate Kubernetes cloud service that's delivered by the team cc @alfredtommy 
- [ ] @mcleo-d to create a 1 hour code review session with @danizheleva for the CSC group to review #60
- [ ] @mcleo-d to create a GitHub Issue to support the offline prioritisation of the next CSC services after Kubernetes

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by adamj-codethink** [comment]
o/

**Comment by RichardWagener365** [comment]
Hi all

**Comment by leefaus** [comment]
here :shipit:

**Comment by phtoth** [comment]
Hello!

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by fleadsom** [comment]
hi :)

**Comment by danizheleva** [comment]
Hello

**Comment by leefaus** [comment]
@mcleo-d did you still want me to talk about Policies for CI/CD and how it pertains to this project?
