### ISSUE TITLE
GCP GKE definition

### ISSUE THREAD

**Issue by peterrhysthomas** [finos/cloud-service-certification#65]
## Completed Issues and Merged Pull Requests
- [x] Delivery of Google Kubernetes Engine (GKE) Service for GCP including Security Command Center #44
- [x] Service Approval Accelerator for GKE service in GCP #48
- [x] Create Terraform scripts for deployment of GKE cluster and node pools as defined in Service Approval Accelerator template
- [x] Creation of peripheral modules
- [x] Testing and validation of above mentioned scripts
- [x] Raise PR request accordingly #73

**Comment by alfredtommy** [comment]
Tasks:

- [ ] Create Terraform scripts for deployment of GKE cluster and node pools as defined in Service Approval Accelerator template

- [ ] Creation of peripheral modules

- [ ] Testing and validation of above mentioned scripts

- [ ] Raise PR request accordingly

**Comment by mcleo-d** [comment]
Thank you @alfredtommy for updating the status in this issue. 

I have taken your points and have added here ... https://github.com/finos/cloud-service-certification/issues/65#issue-704487064

👍

**Comment by mcleo-d** [comment]
@peterrhysthomas and @alfredtommy 

I've taken a look at the success criteria of this issue and it looks like it can be closed.

Can you review and close if appropriate?

James.

**Comment by mcleo-d** [comment]
@peterrhysthomas and @alfredtommy - I have linked this issue to #73 which has been merged previously 👍

**Comment by mcleo-d** [comment]
Issue confirmed as closed by @alfredtommy ...

Congratulations on an issue well done !!! 👏 💯💯💯
