### ISSUE TITLE
AWS EKS definition

### ISSUE THREAD

**Issue by peterrhysthomas** [finos/cloud-service-certification#66]
## Work Items
- [x] Service Accelerator Template for EKS (Kubernetes) on Amazon AWS #76
- [ ] Create scripts for deployment of EKE cluster as defined in Service Approval Accelerator template #113 
- [ ] Testing and validation of above mentioned scripts
- [ ] Raise PR request accordingly

**Comment by abdullahgarcia** [comment]
Hi @peterrhysthomas ,

Thanks for creating the issue.

I'll be looking after this matter.

Regards,

Abdullah

**Comment by mcleo-d** [comment]
Automatically closed, reopening.

**Comment by abdullahgarcia** [comment]
@mcleo-d can we set a meeting for 30th of March at 3.00 pm GMT to review Terraform files please?

**Comment by mcleo-d** [comment]
@abdullahgarcia - Is there anything here for Sprint 4 ?

**Comment by eddie-knight** [comment]
This issue can be closed from the issues on `compliant-financial-infrastructure` once it has been tracked in [terraform-aws-eks](https://github.com/finos/terraform-aws-eks).
