### ISSUE TITLE
24 September 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#71]
## Date
Thursday 24 September 2020 - 10am EST / 3pm BST

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Review action items from previous meetings
- [x] **Group Review Feedback**: @danizheleva - Service Accelerator Template for PostgreSQL on Microsoft Azure https://github.com/finos/cloud-service-certification/pull/60#issuecomment-696153348
- [x] **Azure Kubernetes Service Accelerator**: @tmewett - Define the Service Approval Accelerator for Kubernetes on Azure - #68  
- [x] **New Feature Request**: @tmewett - Consider Asciidoc for document markup - #70 
- [x] [Cloud Service Certification Kanban Review](https://github.com/orgs/finos/projects/1)
- [x] AOB, Q&A & Adjourn (5mins)

## Previous Action Items
- [x] @peterrhysthomas to create an Epic in CSC GitHub Issues that represents the delivery and acceptance criteria of the Kubernetes service across all supported cloud services - #64 
- [x] @alfredtommy to create an issue in GitHub that represents the technical delivery of the Kubernetes service for GCP to supports the pull request that's being raised - #65  
- [x] @abdullahgarcia to create an issue in GitHub that represents the creation of the Service Accelerator Template for the Kubernetes service in AWS  - #66 
- [x] @leefaus to create a GitHub issue that represents the integration of [Pulumi](https://www.pulumi.com/) for BDD test purposes against the next appropriate Kubernetes cloud service that's delivered by the team cc @alfredtommy - #62 
- [x] @mcleo-d to create a 1 hour code review session with @danizheleva for the CSC group to review #60
- [x] @mcleo-d to create a GitHub Issue to support the offline prioritisation of the next CSC services after Kubernetes - #63 

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by leefaus** [comment]
Here :shipit:

**Comment by danizheleva** [comment]
Hello!

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by njwilliams** [comment]
boo

**Comment by mikejstevenson** [comment]
Here!

**Comment by fleadsom** [comment]
hey

**Comment by RichardWagener365** [comment]
Hi

**Comment by iantivey** [comment]
Hi Everyone

**Comment by peterrhysthomas** [comment]
hello

**Comment by anthonygtech** [comment]
Hi.

**Comment by abdullahgarcia** [comment]
Hi.

**Comment by eddie-knight** [comment]
👍 :shipit:

**Comment by tmewett** [comment]
hello!

**Comment by erictice** [comment]
hello

**Comment by lccmaciel** [comment]
Hello
