### ISSUE TITLE
8 October 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#75]
## Date
Thursday 8 October 2020 - 10am EST / 3pm BST

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Cloud Service Certification [Project Kanban](https://github.com/orgs/finos/projects/1) Review
  - [x] @danizheleva : **PostgreSQL PR Update** - Service Accelerator Template for PostgreSQL on Microsoft Azure https://github.com/finos/cloud-service-certification/pull/60#issuecomment-700551767 cc @njwilliams , @abdullahgarcia
  - [x] @alfredtommy : **New GCP GKE PR** - Pull request for GKE TF scripts #73 
  - [x] @tmewett : **New Azure AKS PR** - Add Azure Kubernetes Service Approval Accelerator #72
  - [x] @mcleo-d : Update Kanban Review Agenda Item and Update Untracked Attendees Table #74
- [x] @mindthegab : EDMC Cloud Data Management Workgroup and Cloud Service Certification opportunity
- [x] AOB, Q&A & Adjourn (5mins)

## Outstanding Requests
- [ ] @peterrhysthomas : Team to consider options for OSS Forum, details to be provided by @toshaellison

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by alfredtommy** [comment]
hello

**Comment by mcleo-d** [comment]
🍔 😄

**Comment by anthonygtech** [comment]
Hi.

**Comment by danizheleva** [comment]
Hi :)

**Comment by adamj-codethink** [comment]
:racing_car:

**Comment by njwilliams** [comment]
aloha

**Comment by fleadsom** [comment]
🦍

**Comment by mikejstevenson** [comment]
Ola!

**Comment by toshaellison** [comment]
Present

**Comment by tmewett** [comment]
Hi

**Comment by lccmaciel** [comment]
Hi.
