### ISSUE TITLE
22 October 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#77]
## Date
Thursday 22 October 2020 - 10am EST / 3pm BST

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|
| Alexander Molev | Cloudify | |

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Cloud Service Certification [Project Kanban](https://github.com/orgs/finos/projects/1) Review ... _including_ ...
  - [x] **Question** : Can we merge Service Accelerator Template for PostgreSQL on Microsoft Azure #60 ..? @danizheleva and @peterrhysthomas 
  - [x] **New PR Raised** : EKS by @abdullahgarcia #76
  - [x] **Feedback in Comments** : Add Azure Kubernetes Service Approval Accelerator https://github.com/finos/cloud-service-certification/pull/72#pullrequestreview-514376539 @alfredtommy and @tmewett
  - [x] **Next Steps** : Pull request for GKE TF scripts #73 - @mcleo-d and @alfredtommy - Proposed group review **Wednesday 4th November @ 2pm UK / 10am ET** - https://finos.webex.com/meet/community 
- [x] Meeting Moved : **5th November Now @ 12pm ET / 5pm UK** #78
- [x] AOB, Q&A & Adjourn (5mins)

## Actions
- [x] @mcleo-d and @alfredtommy to organise pull request review of GKE TF scripts #73 for **Wednesday 4th November @ 2pm UK / 9am ET** whilst inviting the wider community
- [x] @mcleo-d to rename PR #76 from **EKS** to **Service Accelerator Template for EKS (Kubernetes) on Amazon AWS** 
- [ ] @eddie-knight to form an opinion and report the viability of **Pulumi and BDD Tests** #62 including @leefaus & @alfredtommy 
- [ ] @tmewett to move forward with **Consider Asciidoc for document markup** #70 by combining with #72 if viable and appropriate.

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by mcleo-d** [comment]
Hello! :)

**Comment by eddie-knight** [comment]
👋 :shipit:

**Comment by danizheleva** [comment]
bonjour :)

**Comment by adamj-codethink** [comment]
:wave:

**Comment by peterrhysthomas** [comment]
hello everyone

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by tmewett** [comment]
:wave:

**Comment by anthonygtech** [comment]
Hello.

**Comment by fleadsom** [comment]
hi

**Comment by alexmolev** [comment]
Hello
