### ISSUE TITLE
EPIC - Define EDMC/CDMC Evaluation Docs and Working Cadence

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#81]
## Definition and Delivery of EDMC/CDMC Evaluation Docs and Working Cadence

- [x] CDMC introduction to CSC (#78) - **Oli Bage** & **Richard Perris**
- [ ] Provide CSC with working version of `Data Encryption – In transit, at rest, and while in use` document - **Richard Perris**
- [ ] Distribute working version of `Data Encryption – In transit, at rest, and while in use` document to CSC members - @mcleo-d 
- [ ] CDMC and CSC to define working relationship and cadence - @peterrhysthomas @abdullahgarcia & **Richard Perris**
- [ ] Present working relationship and cadence proposal to EDMC - @peterrhysthomas @abdullahgarcia & **Richard Perris**

**Comment by fleadsom** [comment]
@fleadsom on behalf of @peterrhysthomas and @danizheleva

**Comment by mcleo-d** [comment]
> @fleadsom on behalf of @peterrhysthomas and @danizheleva

This is to confirm the team named in this comment has been forwarded the DRAFT CDMC **Securing Data - 3.1 Data should be encrypted at rest, in motion and in use vEAB0710** document for review and feedback.

Please do not distribute or forward this document without permission from the CDMC.

**Comment by mcleo-d** [comment]
This is to confirm @leefaus has been forwarded the DRAFT CDMC **Securing Data - 3.1 Data should be encrypted at rest, in motion and in use vEAB0710** document for review and feedback as requested at #93.

Please do not distribute or forward this document without permission from the CDMC.

**Comment by eddie-knight** [comment]
:wave: :shipit: Could I get looped in on this?

**Comment by mcleo-d** [comment]
This is to confirm @eddie-knight and @TLATER have been forwarded the DRAFT CDMC Securing Data - 3.1 Data should be encrypted at rest, in motion and in use vEAB0710 document for review and feedback as requested.

Please do not distribute or forward this document without permission from the CDMC.
